spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssmp?serverTimezone=UTC
      username: zhangxu
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource

  devtools:
    restart:
      exclude: static/**,public/**

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      id-type: auto
debug: true
